apiVersion: v1
kind: Secret
metadata:
  name: web-book-backend-secret
  namespace: app-web-book-dev
  labels:
    app: web-book-backend
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/web-book-dev"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: app-web-book-dev
  labels:
    app: web-book
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<GITHUB_USER>",
          "password": "<GITHUB_PAT>",
          "email": "<GITHUB_EMAIL>",
          "auth": "<BASE64_USER_COLON_PAT>"
        }
      }
    }
